name: go-hospital-api

services:
  db:
    container_name: database
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hospitaldb
    ports:
      - "5400:5432"

volumes:
  db_data:
    name: db_data